# Generated by Django 3.2.12 on 2022-02-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del contrato')),
                ('fecha', models.DateField(verbose_name='Fecha del contrato')),
                ('archivo', models.FileField(upload_to='contracts/', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=150, verbose_name='Puerto de origen')),
                ('destination', models.CharField(max_length=150, verbose_name='Puerto de dstino')),
                ('currency', models.CharField(max_length=150, verbose_name='Moneda')),
                ('twenty', models.CharField(max_length=150, verbose_name='20’GP')),
                ('forty', models.CharField(max_length=150, verbose_name='40’GP')),
                ('fortyhc', models.CharField(max_length=150, verbose_name='40’HC')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contrato', to='contracts.contracts')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
